version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000' # Puerto de la aplicaci贸n
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/taller1  # Conexi贸n a la base de datos MongoDB
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod # Comando para iniciar la aplicaci贸n en modo producci贸n

  mongo:
    image: mongo:latest  # Imagen oficial de MongoDB
    container_name: mongodb
    ports:
      - '27017:27017'  # Puerto de MongoDB
    volumes:
      - ./mongo-data:/data/db  # Volumen persistente para los datos de MongoDB
